services:
  ia_gateway:
    build: .
    # O comando agora inicia o novo script do servidor diretamente
    command: uvicorn servidor_gateway_nuvem:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    working_dir: /app